compute:
  device: !!python/object/apply:torch.device
  - mps
  mixed_precision: true
  num_threads: 4
  requested_device: auto
experiment:
  comment: ''
  name: xor-32_continuous-persist-no-dead-samples-in-pool-ES
  seed: 12
  version_used: a610cd1
misc:
  debug: true
  preview_target_image: false
model:
  alive_threshold: 0.1
  fire_rate: 0.5
  landmarks:
    params: {}
    type: none
  num_channels: 16
  num_hidden: 12
  num_visible: 3
  seed_alpha: 1.0
  step_size: 1.0
results:
  batch_images:
    enabled: true
    interval: 100
  ca_rollout:
    ca_steps: 1200
    enabled: true
    fps: 30
    use_best_checkpoint: false
  channel_strip:
    cmap_name: viridis
    enabled: false
    font_size: 8
    for_train_step: 1
    interval: 1
    spacing: 4
  metrics:
    interval: 10
    rollout_metrics: null
  model_checkpoint:
    interval: 1000
  output_dir: results/2025-09-16/170033_xor-32_continuous-persist-no-dead-samples-in-pool-ES
  pool_images:
    enabled: true
    fps: 10
    interval: 100
    video: true
target:
  target_emoji: null
  target_image: data/targets/wireworld/golly-xor-32.png
  target_padding: 16
  target_size: 32
training:
  batch_size: 8
  early_stopping:
    enabled: true
    measure: accuracy
    min_delta: 1e-4
    patience: 250
    warmup_steps: 500
    window_size: 100
  epsilon: 1e-7
  learning_rate: 2e-3
  mode: continuous
  num_steps: 8001
  num_to_damage: 0
  optimizer: adam
  pool_commit_prob: 1.0
  pool_commit_tolerance: 0.1
  pool_size: 1024
  replace_with_seed: 1
  rollout:
    alpha_scaling: null
    max: 96
    min: 64
    starting_step_size: null
    warmup_steps: null
  scheduler:
    decay_factor: 0.1
    milestones:
    - 2000
    warmup_steps: null
  supervise_wireworld: false
